title: Typetron - Fully-featured Node.js framework
email: ionel@typetron.org
description: >- # this means to ignore newlines until "baseurl:"
    Typetron - Modern Fully-featured Typescript Framework for Node.js for building enterprise level web apps
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://typetron.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ionelCLupu
github_username:  ionellupu

# Build settings
markdown: kramdown
kramdown:
    input: GFM

theme: minima
plugins:
    - jekyll-feed

sass:
    sass_dir: style/scss

collections:
    - docs
    - tutorials
